import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { buildFallbackCircleDataFromActivity, type DosCircleData, type DosRelationshipScore } from "@/src/lib/dos/circle-scoring";
import {
  type DosAppData,
  type DosAppAssessmentResult,
  type DosAppFruit,
  type DosAppFruitEvent,
  type DosAppLeaderReflection,
  type DosAppMeeting,
  type DosAppParticipantReview,
  type DosAppParticipantTestimony,
  type DosAppPerson,
  type DosAppRelationshipReminder,
} from "@/src/lib/dos/missionary-app";
import { normalizeRelationshipType, relationshipModelCounts } from "@/src/lib/dos/relationship-model";
import { DosMobileMessageScreen } from "../DosMobileMessageScreen";
import { DosMvpAppClient } from "../DosMvpAppClient";
import { PrimitivesGallery } from "./PrimitivesGallery";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Preview",
  robots: {
    follow: false,
    index: false,
  },
};

// Optional smoke-test route only. The live `/dos/[slug]` workspace is the
// primary DOS testing and demo surface; keep this data synthetic and keep UI
// changes in the shared DosMvpAppClient.
const demoTimestamp = "2026-05-27T10:30:00-05:00";
const demoWorkspaceId = "00000000-0000-4000-8000-000000000070";
const demoAccessToken = process.env.DOS_PREVIEW_TOKEN?.trim() || "dos2026";
const isDemoPreviewRouteEnabled = process.env.DOS_DISABLE_DEMO_PREVIEW !== "true";
// Most of this fixture is pinned to a fixed demo date so recorded history reads naturally.
// The deterministic circle-suggestion rolling windows (14/30 days) compare against the real
// clock, so a handful of meetings below are dated relative to "today" instead of the fixed
// demo date — otherwise every meeting in this fixture would already be outside every window.
function daysAgoIso(days: number, hour = 9, minute = 0) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}
type DemoMeetingInput = Omit<DosAppMeeting, "googleSyncEnabled" | "googleSyncStatus" | "growthReflection" | "meetingStatus" | "ministryEventId" | "ministryTeam" | "participants" | "planningReflection" | "recorder" | "reviewLinks" | "scheduledEndAt" | "scheduledStartAt" | "supportingAttendees" | "tableRole" | "timezone">
  & Partial<Pick<DosAppMeeting, "googleSyncEnabled" | "googleSyncStatus" | "growthReflection" | "meetingStatus" | "ministryEventId" | "ministryTeam" | "participants" | "planningReflection" | "recorder" | "reviewLinks" | "scheduledEndAt" | "scheduledStartAt" | "supportingAttendees" | "tableRole" | "timezone">>;
const emptyGrowthReflection: DosAppMeeting["growthReflection"] = {
  actionStep: null,
  followUpNeeded: false,
  mentorAssignment: null,
  scriptures: null,
  whatGodTaught: null,
};
const emptyPlanningReflection: DosAppMeeting["planningReflection"] = {
  actionItems: null,
  decisions: null,
  followUp: null,
};

function LockedPreviewScreen() {
  return (
    <DosMobileMessageScreen eyebrow="DOS Preview" title="Enter demo access code.">
      <form action="/dos/app/preview" className="space-y-3" method="get">
        <label className="block">
          <span className="text-xs font-semibold text-[#64748B]">Access code</span>
          <input
            autoComplete="off"
            className="mt-2 min-h-12 w-full rounded-2xl border border-[#E2E8F0] bg-[#F1F5F9] px-4 text-sm font-medium text-[#0F172A] outline-none transition-colors placeholder:text-[#94A3B8] focus:border-[#2563EB]"
            name="demo"
            placeholder="Enter code"
            type="password"
          />
        </label>
        <button
          className="inline-flex min-h-12 w-full items-center justify-center rounded-full bg-[linear-gradient(135deg,#2563EB_0%,#1D4ED8_100%)] px-4 text-sm font-bold text-white shadow-[0_12px_28px_rgba(37,99,235,0.24)]"
          type="submit"
        >
          Open Preview
        </button>
      </form>
    </DosMobileMessageScreen>
  );
}

function buildDemoReview(status: DosAppMeeting["review"]["status"] = "not_sent", stoodOut: string | null = null): DosAppMeeting["review"] {
  return {
    overallRating: status === "not_sent" ? null : "very_meaningful",
    sharePermission: status === "approved" ? "internal" : null,
    status,
    stoodOut,
    submittedAt: status === "not_sent" ? null : demoTimestamp,
    submittedName: status === "not_sent" ? null : "Ryan Fox",
    token: null,
  };
}

function buildDemoMeeting(meeting: DemoMeetingInput): DosAppMeeting {
  return {
    googleSyncEnabled: false,
    googleSyncStatus: null,
    growthReflection: emptyGrowthReflection,
    meetingStatus: "logged",
    ministryEventId: null,
    ministryTeam: [],
    participants: [],
    planningReflection: emptyPlanningReflection,
    recorder: null,
    reviewLinks: [],
    scheduledEndAt: null,
    scheduledStartAt: null,
    supportingAttendees: [],
    tableRole: "ministering",
    timezone: "America/Chicago",
    ...meeting,
  };
}

// Simulates a locked dos_circle_overrides row (see src/lib/dos/circle-scoring.ts) so the demo
// can show a person who was manually placed in a circle and stays there even as their own
// recent activity outpaces it — the exact scenario Deterministic Circle Logic V1 is meant to
// surface as a suggestion rather than an automatic move.
function withManualCircleOverride(
  circleData: DosCircleData,
  personId: string,
  targetCircle: "field" | "my_120" | "seventy" | "three" | "twelve",
  reason: string,
): DosCircleData {
  const listByCircle = {
    field: circleData.field,
    my_120: circleData.my120,
    seventy: circleData.my70,
    three: circleData.my3,
    twelve: circleData.my12,
  };
  let overriddenScore: DosRelationshipScore | undefined;
  const remainingByCircle = Object.fromEntries(Object.entries(listByCircle).map(([circle, list]) => [
    circle,
    list.filter((score) => {
      if (score.person.id !== personId) {
        return true;
      }

      overriddenScore = score;
      return false;
    }),
  ])) as typeof listByCircle;

  if (!overriddenScore) {
    return circleData;
  }

  remainingByCircle[targetCircle] = [
    ...remainingByCircle[targetCircle],
    {
      ...overriddenScore,
      assignmentSource: "manual",
      circle: targetCircle,
      explanation: { ...overriddenScore.explanation, summary: reason },
    },
  ];

  return {
    ...circleData,
    field: remainingByCircle.field,
    my12: remainingByCircle.twelve,
    my120: remainingByCircle.my_120,
    my3: remainingByCircle.three,
    my70: remainingByCircle.seventy,
  };
}

function buildDosPreviewDemoData(): DosAppData {
  const people: DosAppPerson[] = [
    {
      church: "City Chapel",
      createdAt: "2026-05-06T09:15:00-05:00",
      email: "george.jenko@example.com",
      discipleshipRelationship: "mentee",
      discipleshipStage: "disciple_maker",
      engagementLevel: "High",
      fieldVisibility: "primary",
      spouseName: "Mara Jenko",
      childrenNames: "Liam, Nora",
      householdNotes: "Friday evenings are best for family follow-up.",
      id: "demo-person-george-jenko",
      lastActivityAt: "2026-05-27T08:15:00-05:00",
      name: "George Jenko",
      notes: "Hungry for Scripture and steady in follow-through.\n\nAdditional information:\nHome address: 842 North Ash Ave, Tulsa, OK 74120\nOccupation: Firefighter\nBirthday: 1989-04-11",
      phone: "918-555-0147",
      relationshipContext: "church",
      relationshipType: "Disciple",
      relationshipTypeValue: "discipling",
      roleInMyLife: "discipling_them",
      status: "active",
      updatedAt: demoTimestamp,
    },
    {
      church: "Redemption Church",
      createdAt: "2026-05-08T11:00:00-05:00",
      email: "brooke.fox@example.com",
      discipleshipRelationship: "peer",
      discipleshipStage: "walking_with",
      engagementLevel: "High",
      fieldVisibility: "primary",
      id: "demo-person-brooke-fox",
      lastActivityAt: "2026-05-25T18:30:00-05:00",
      name: "Brooke Fox",
      notes: "Consistent prayer partner and helps host table conversations.",
      phone: "918-555-0182",
      relationshipContext: "family",
      relationshipType: "Co-laborer",
      relationshipTypeValue: "walking_with",
      roleInMyLife: "peer_encouragement",
      status: "active",
      updatedAt: demoTimestamp,
    },
    {
      church: null,
      createdAt: "2026-05-10T14:45:00-05:00",
      email: "tim.tran@example.com",
      discipleshipRelationship: null,
      discipleshipStage: "exploring",
      engagementLevel: "Medium",
      fieldVisibility: "primary",
      id: "demo-person-tim-tran",
      lastActivityAt: "2026-05-24T16:00:00-05:00",
      name: "Tim Tran",
      notes: "New to Bible reading. Wants a simple next step after work.",
      phone: "918-555-0121",
      relationshipContext: "work",
      relationshipType: "Coworker",
      relationshipTypeValue: "walking_with",
      roleInMyLife: "walking_with_them",
      status: "active",
      updatedAt: demoTimestamp,
    },
    {
      // Household and personal fields are stored the way the Person form
      // writes them (spouse/children columns, plus the "Additional
      // information" block the form encodes into notes) so Details renders
      // from the real shape rather than a prototype-only structure.
      childrenNames: "Ellie (7), Sam (4)",
      church: "River Valley Church",
      createdAt: "2026-05-12T10:10:00-05:00",
      email: "naomi.lee@example.com",
      discipleshipRelationship: null,
      discipleshipStage: "exploring",
      engagementLevel: "Medium",
      fieldVisibility: "primary",
      householdNotes: "Her sister Dana lives two streets over and has started asking questions.",
      id: "demo-person-naomi-lee",
      lastActivityAt: "2026-05-14T12:15:00-05:00",
      name: "Naomi Lee",
      notes: "Asked for prayer after the coffee meeting. Follow up this week.\n\nAdditional information:\nHome address: 1412 Birch Lane, Tulsa, OK 74104\nOccupation: Dental hygienist\nBirthday: 1991-03-18",
      phone: "918-555-0166",
      spouseName: "Marcus Lee",
      relationshipContext: "community",
      relationshipType: "Neighbor",
      relationshipTypeValue: "walking_with",
      roleInMyLife: "walking_with_them",
      status: "follow_up",
      updatedAt: demoTimestamp,
    },
    {
      church: "Grace Fellowship",
      createdAt: "2026-05-23T15:20:00-05:00",
      email: "caleb.rivera@example.com",
      discipleshipRelationship: null,
      discipleshipStage: "not_started",
      engagementLevel: "Low",
      fieldVisibility: "primary",
      id: "demo-person-caleb-rivera",
      lastActivityAt: "2026-05-23T15:20:00-05:00",
      name: "Caleb Rivera",
      notes: "Met through George. Open to joining a kitchen table soon.",
      phone: "918-555-0194",
      relationshipContext: "outreach",
      relationshipType: "New contact",
      relationshipTypeValue: "new",
      roleInMyLife: "not_active",
      status: "new",
      updatedAt: demoTimestamp,
    },
    // Acceptance fixture: a real first mentoring meeting. Philip asked to be
    // mentored during a 2h30m first meeting; the mentoring relationship and
    // monthly cadence are recorded on the Person, homework became
    // Accountability, and the next meeting is scheduled. Encouraging him to
    // begin discipling other men is Accountability — NOT Fruit, because
    // nothing has been observed yet.
    {
      church: "Redemption Church",
      createdAt: daysAgoIso(6),
      email: "philip.saco@example.com",
      discipleshipRelationship: "mentee",
      discipleshipStage: "walking_with",
      engagementLevel: "High",
      fieldVisibility: "primary",
      id: "demo-person-philip-saco",
      lastActivityAt: daysAgoIso(6),
      meetingRhythm: "Monthly",
      name: "Philip John Saco",
      notes: "Asked to be mentored after the men's breakfast.",
      phone: "918-555-0173",
      relationshipContext: "church",
      relationshipType: "discipling",
      relationshipTypeValue: "discipling",
      roleInMyLife: "discipling_them",
      status: "active",
      updatedAt: demoTimestamp,
    },
    // Kept from main: Tanner backs the Wednesday Men's Group Journey QA.
    {
      church: "Wednesday Men's Group",
      createdAt: "2026-08-10T18:15:00-05:00",
      email: "tanner.kent@example.com",
      discipleshipRelationship: null,
      discipleshipStage: "not_started",
      engagementLevel: "Medium",
      fieldVisibility: "primary",
      id: "demo-person-tanner-kent",
      lastActivityAt: "2026-08-10T18:15:00-05:00",
      name: "Tanner Kent",
      notes: "Demo-safe participant for Wednesday Men's Group Journey launch QA.",
      phone: "918-555-0174",
      relationshipContext: "church",
      relationshipType: "Group member",
      relationshipTypeValue: "walking_with",
      roleInMyLife: "walking_with_them",
      status: "active",
      updatedAt: demoTimestamp,
    },
  ];

  const meetingInputs = [
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(6, 10),
      fieldPersonIds: ["demo-person-philip-saco"],
      growthReflection: emptyGrowthReflection,
      id: "demo-meeting-philip-first",
      notes: "Philip asked me to mentor him. We talked through where he is with God, his marriage, and the men he already has influence with. Agreed to meet monthly.",
      participantNames: ["Philip John Saco"],
      recommendedResources: [],
      review: buildDemoReview(),
      scheduledEndAt: daysAgoIso(6, 12, 30),
      scheduledStartAt: daysAgoIso(6, 10),
      source: "table",
      title: "First mentoring meeting",
      type: "kitchen_table",
      updatedAt: daysAgoIso(6, 13),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(-24, 13),
      fieldPersonIds: ["demo-person-philip-saco"],
      googleSyncEnabled: false,
      id: "demo-meeting-philip-next",
      meetingStatus: "scheduled",
      notes: "",
      participantNames: ["Philip John Saco"],
      recommendedResources: [],
      review: buildDemoReview(),
      scheduledEndAt: daysAgoIso(-24, 14),
      scheduledStartAt: daysAgoIso(-24, 13),
      source: "table",
      timezone: "America/Chicago",
      title: "In person",
      type: "kitchen_table",
      updatedAt: demoTimestamp,
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(-3, 18),
      fieldPersonIds: ["demo-person-naomi-lee"],
      googleSyncEnabled: true,
      googleSyncStatus: "pending",
      id: "demo-meeting-naomi-scheduled",
      meetingStatus: "scheduled",
      notes: "Ask about her family. Bring the John reading plan.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      scheduledEndAt: daysAgoIso(-3, 19),
      scheduledStartAt: daysAgoIso(-3, 18),
      source: "table",
      timezone: "America/Chicago",
      title: "Coffee",
      type: "coffee",
      updatedAt: daysAgoIso(0),
    },
    {
      conversationFlowKey: "kitchen_table_gospel",
      conversationResponses: {
        attendChurchOften: "yes",
        baptized: "yes",
        believeJesus: "yes",
        bibleDaily: "yes",
        disciplingAnyone: "yes",
        honorSabbath: "unsure",
        prayFastOften: "yes",
        preachGoodNews: "yes",
        spiritualGifts: "unsure",
        tithe: "yes",
      },
      date: "2026-05-27T08:15:00-05:00",
      fieldPersonIds: ["demo-person-george-jenko"],
      id: "demo-meeting-george-scripture",
      notes: "Read Luke 10 together and talked through who George is praying for this week.",
      participantNames: ["George Jenko"],
      recommendedResources: [
        { id: "discipleship", reason: "George wants a repeatable framework for new believers.", status: "queued", title: "Discipleship", type: "resource" },
      ],
      review: buildDemoReview("approved", "George is beginning to think beyond his own growth and name people he can disciple."),
      source: "table",
      title: "Morning Scripture",
      type: "discipleship",
      updatedAt: "2026-05-27T09:00:00-05:00",
    },
    {
      conversationFlowKey: "four_questions",
      conversationResponses: {
        conversation_notes: "Brooke helped guide the conversation and Tim stayed engaged.",
        needs_outside_help: "yes",
        recognizes_problem: "yes",
        response_notes: "Tim resonated with needing help outside himself.",
        willing_to_follow_through: "unsure",
        willing_to_receive_help: "yes",
      },
      date: "2026-05-25T18:30:00-05:00",
      fieldPersonIds: ["demo-person-george-jenko", "demo-person-brooke-fox", "demo-person-tim-tran"],
      id: "demo-meeting-table-george-brooke-tim",
      notes: "Kitchen table night. Tim asked honest questions and George shared part of his story.",
      participantNames: ["George Jenko", "Brooke Fox", "Tim Tran"],
      recommendedResources: [
        { id: "attending-church", reason: "Tim wants a next conversation about following Jesus.", status: "queued", title: "Attending Church", type: "resource" },
      ],
      review: buildDemoReview("submitted", "Tim is open and Brooke is helping create a warm space for follow up."),
      source: "table",
      title: "Kitchen Table",
      type: "kitchen_table",
      updatedAt: "2026-05-25T20:00:00-05:00",
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: "2026-05-24T16:00:00-05:00",
      fieldPersonIds: ["demo-person-tim-tran"],
      id: "demo-meeting-tim-coffee",
      notes: "Coffee after work. Tim wants to start reading John and asked for prayer for courage.",
      participantNames: ["Tim Tran"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Coffee",
      type: "coffee",
      updatedAt: "2026-05-24T17:10:00-05:00",
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: "2026-05-23T15:20:00-05:00",
      fieldPersonIds: ["demo-person-caleb-rivera"],
      id: "demo-meeting-caleb-intro",
      notes: "Met Caleb through George. He is curious and open to joining next month's table.",
      participantNames: ["Caleb Rivera"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Intro Coffee",
      type: "coffee",
      updatedAt: "2026-05-23T16:00:00-05:00",
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: "2026-05-22T12:00:00-05:00",
      fieldPersonIds: ["demo-person-brooke-fox"],
      id: "demo-meeting-brooke-prayer",
      notes: "Prayed over the upcoming table and named two people to invite.",
      participantNames: ["Brooke Fox"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "connection",
      title: "Prayer Check-In",
      type: "prayer",
      updatedAt: "2026-05-22T12:30:00-05:00",
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: "2026-05-21T07:30:00-05:00",
      fieldPersonIds: ["demo-person-george-jenko"],
      id: "demo-meeting-george-coffee",
      notes: "Followed up on baptism and daily prayer rhythms.",
      participantNames: ["George Jenko"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Coffee",
      type: "coffee",
      updatedAt: "2026-05-21T08:10:00-05:00",
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: "2026-05-19T19:00:00-05:00",
      fieldPersonIds: ["demo-person-george-jenko", "demo-person-brooke-fox"],
      id: "demo-meeting-george-brooke-discipleship",
      notes: "Practiced sharing the gospel simply and prayed for George's brother.",
      participantNames: ["George Jenko", "Brooke Fox"],
      recommendedResources: [],
      review: buildDemoReview("approved", "George is growing in confidence and Brooke is actively investing."),
      source: "table",
      growthReflection: {
        actionStep: "Practice the gospel outline once this week.",
        followUpNeeded: false,
        mentorAssignment: null,
        scriptures: "Luke 10",
        whatGodTaught: "Mutual practice made the next conversation feel simple and repeatable.",
      },
      tableRole: "mutual_discipleship",
      title: "Discipleship Practice",
      type: "discipleship",
      updatedAt: "2026-05-19T20:10:00-05:00",
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: "2026-05-14T12:15:00-05:00",
      fieldPersonIds: ["demo-person-naomi-lee"],
      id: "demo-meeting-naomi-coffee",
      notes: "Naomi shared about family pressure and asked for prayer. Follow up is needed.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Coffee",
      type: "coffee",
      updatedAt: "2026-05-14T13:00:00-05:00",
    },
    // Recent-window fixtures for the deterministic Circle Logic V1 prototype (see comment on
    // daysAgoIso above). These give the My 3 circle a non-zero rolling benchmark and give Naomi
    // a sustained one-to-one pattern that clears it, so "Consider moving closer" has real,
    // computed evidence to show rather than an empty state.
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(22),
      fieldPersonIds: ["demo-person-george-jenko"],
      id: "demo-meeting-george-recent-checkin",
      notes: "Quick check-in on the discipleship group he is starting.",
      participantNames: ["George Jenko"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Check-In",
      type: "coffee",
      updatedAt: daysAgoIso(22),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(26),
      fieldPersonIds: ["demo-person-brooke-fox"],
      id: "demo-meeting-brooke-recent-checkin",
      notes: "Prayed together before the next kitchen table.",
      participantNames: ["Brooke Fox"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "connection",
      title: "Prayer Check-In",
      type: "prayer",
      updatedAt: daysAgoIso(26),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(18),
      fieldPersonIds: ["demo-person-tim-tran"],
      id: "demo-meeting-tim-recent-checkin",
      notes: "Followed up on the John reading plan.",
      participantNames: ["Tim Tran"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Coffee",
      type: "coffee",
      updatedAt: daysAgoIso(18),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(2),
      fieldPersonIds: ["demo-person-naomi-lee"],
      growthReflection: {
        actionStep: "Read John 4-6 before Thursday",
        followUpNeeded: false,
        mentorAssignment: null,
        scriptures: "John 3",
        whatGodTaught: null,
      },
      id: "demo-meeting-naomi-recent-1",
      notes: "Naomi shared that her family asked why she's different lately.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "John reading plan",
      type: "coffee",
      updatedAt: daysAgoIso(2),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(4),
      fieldPersonIds: ["demo-person-naomi-lee"],
      id: "demo-meeting-naomi-recent-2",
      notes: "Prayed together about her family situation.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "connection",
      title: "Prayer Check-In",
      type: "prayer",
      updatedAt: daysAgoIso(4),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(6),
      fieldPersonIds: ["demo-person-naomi-lee"],
      id: "demo-meeting-naomi-recent-3",
      notes: "Continued the John reading plan.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Coffee",
      type: "coffee",
      updatedAt: daysAgoIso(6),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(8),
      fieldPersonIds: ["demo-person-naomi-lee"],
      id: "demo-meeting-naomi-recent-4",
      notes: "Talked through what she is learning and next steps.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Discipleship Conversation",
      type: "discipleship",
      updatedAt: daysAgoIso(8),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(10),
      fieldPersonIds: ["demo-person-naomi-lee"],
      id: "demo-meeting-naomi-recent-5",
      notes: "Coffee and prayer before her family visit.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "connection",
      title: "Prayer Check-In",
      type: "prayer",
      updatedAt: daysAgoIso(10),
    },
    {
      conversationFlowKey: "none",
      conversationResponses: {},
      date: daysAgoIso(12),
      fieldPersonIds: ["demo-person-naomi-lee"],
      id: "demo-meeting-naomi-recent-6",
      notes: "Checked in on the family follow-up from last month.",
      participantNames: ["Naomi Lee"],
      recommendedResources: [],
      review: buildDemoReview(),
      source: "table",
      title: "Coffee",
      type: "coffee",
      updatedAt: daysAgoIso(12),
    },
  ] satisfies DemoMeetingInput[];
  // Matches production ordering (missionary_tables is always queried `order("table_date", { ascending: false })`)
  // so "last meeting" logic sees the true most-recent entry regardless of fixture declaration order.
  const meetings = meetingInputs
    .map(buildDemoMeeting)
    .sort((first, second) => new Date(second.date ?? 0).getTime() - new Date(first.date ?? 0).getTime());

  const fruit: DosAppFruit[] = [
    {
      fieldPersonId: "demo-person-george-jenko",
      id: "demo-fruit-george-discipling",
      outcomeTags: ["Joined Discipleship", "Started Discipling Others"],
      permissionToShare: true,
      sourceApp: "dos_preview",
      status: "approved",
      submittedByName: "Ryan Fox",
      summary: "George named two people he wants to begin discipling and committed to meeting weekly.",
      tableId: "demo-meeting-george-scripture",
      testimonyDate: "2026-05-27T09:00:00-05:00",
      updatedAt: demoTimestamp,
    },
  ];

  const fruitEvents: DosAppFruitEvent[] = [
    {
      confidenceLevel: "verified",
      date: "2026-05-27T09:00:00-05:00",
      debugContext: {},
      description: "George is preparing to disciple his brother and a coworker.",
      fruitType: "Started Discipling Others",
      generatedBy: "DOS Preview",
      generationKey: "demo-george-multiplication",
      id: "demo-fruit-event-george-multiplication",
      meetingId: "demo-meeting-george-scripture",
      personId: "demo-person-george-jenko",
      sourceId: "demo-reflection-george-scripture",
      sourceType: "leader_reflection",
      status: "approved",
      title: "George began multiplying",
      visibility: "internal",
    },
    // Naomi's arc: family pressure -> prayer -> her family asks why she is
    // different -> she tells them. Recorded from the leader reflection on the
    // meeting where it happened, so Fruit, Timeline and the meeting record all
    // resolve to the same canonical event.
    {
      confidenceLevel: "observed",
      date: daysAgoIso(2, 9),
      debugContext: {},
      description: "Naomi told her sister why her life has changed since she started following Jesus.",
      fruitType: "Gospel conversation",
      generatedBy: "DOS Preview",
      generationKey: "demo-naomi-gospel-conversation",
      id: "demo-fruit-event-naomi-gospel-conversation",
      meetingId: "demo-meeting-naomi-recent-1",
      personId: "demo-person-naomi-lee",
      sourceId: "demo-reflection-naomi-recent-1",
      sourceType: "leader_reflection",
      status: "approved",
      title: "Gospel conversation with her sister",
      visibility: "internal",
    },
    {
      confidenceLevel: "confirmed",
      date: daysAgoIso(30, 9),
      debugContext: {},
      description: "Naomi committed to a weekly discipleship rhythm and started the Discipleship journey.",
      fruitType: "Joined Discipleship",
      generatedBy: "DOS Preview",
      generationKey: "demo-naomi-joined-discipleship",
      id: "demo-fruit-event-naomi-joined-discipleship",
      meetingId: "demo-meeting-naomi-coffee",
      personId: "demo-person-naomi-lee",
      sourceId: "demo-reflection-naomi-follow-up",
      sourceType: "leader_reflection",
      status: "approved",
      title: "Joined Discipleship",
      visibility: "internal",
    },
  ];

  const leaderReflections: DosAppLeaderReflection[] = [
    {
      createdAt: "2026-05-27T09:00:00-05:00",
      followUpNeeded: false,
      id: "demo-reflection-george-scripture",
      meetingId: "demo-meeting-george-scripture",
      nextStep: "Begin discipleship",
      observedFruit: ["Started Discipling Others"],
      personId: "demo-person-george-jenko",
      prayerNeeds: "Pray for courage as George invites his brother into a weekly rhythm.",
      privateNotes: "Keep George close this week and help him prepare his first conversation.",
      spiritualOpenness: "Actively following",
      whatHappened: "George moved from receiving discipleship to naming people he can invest in.",
    },
    {
      createdAt: "2026-05-14T13:00:00-05:00",
      followUpNeeded: true,
      id: "demo-reflection-naomi-follow-up",
      meetingId: "demo-meeting-naomi-coffee",
      nextStep: "Send follow up",
      observedFruit: ["Prayer Request"],
      personId: "demo-person-naomi-lee",
      prayerNeeds: "Naomi asked for peace and wisdom with her family.",
      privateNotes: "Send a text and invite Naomi to coffee again.",
      spiritualOpenness: "Open",
      whatHappened: "Naomi was honest and receptive, but needs a gentle follow up.",
    },
    {
      createdAt: daysAgoIso(2, 9),
      followUpNeeded: true,
      id: "demo-reflection-naomi-recent-1",
      meetingId: "demo-meeting-naomi-recent-1",
      nextStep: "Read John 4-6 before Thursday",
      observedFruit: ["Gospel Conversation"],
      personId: "demo-person-naomi-lee",
      prayerNeeds: "Pray for Naomi's sister, and for courage in the next conversation.",
      privateNotes: "She was nervous telling her sister but did it anyway. Encourage her.",
      spiritualOpenness: "Actively following",
      whatHappened: "Naomi's family asked why she is different lately, and she told her sister about Jesus.",
    },
  ];

  const participantReviews: DosAppParticipantReview[] = [
    {
      comments: "I felt cared for and want to keep meeting.",
      conversationHelpful: "yes",
      feltCaredFor: "yes",
      feltHeard: "yes",
      id: "demo-participant-review-tim",
      meetingId: "demo-meeting-table-george-brooke-tim",
      overallRating: "very_meaningful",
      outcomeTags: ["Encouragement", "Discipling"],
      personId: "demo-person-tim-tran",
      status: "approved",
      submittedAt: "2026-05-25T21:10:00-05:00",
      submittedEmail: null,
      submittedFirstName: "Tim",
      submittedLastName: "Tran",
      submittedName: "Tim Tran",
      wantsFollowUp: null,
      wouldMeetAgain: true,
      wouldMeetAgainResponse: "yes",
    },
    {
      comments: "Having someone actually ask about my family made it easier to talk to them myself.",
      conversationHelpful: "yes",
      feltCaredFor: "yes",
      feltHeard: "yes",
      id: "demo-participant-review-naomi",
      meetingId: "demo-meeting-naomi-recent-3",
      overallRating: "very_meaningful",
      outcomeTags: ["Encouragement", "Discipling"],
      personId: "demo-person-naomi-lee",
      status: "approved",
      submittedAt: daysAgoIso(5, 20),
      submittedEmail: null,
      submittedFirstName: "Naomi",
      submittedLastName: "Lee",
      submittedName: "Naomi Lee",
      /* She asked to be contacted -- the one thing that must be impossible to
         miss on the Person. */
      wantsFollowUp: "yes",
      wouldMeetAgain: true,
      wouldMeetAgainResponse: "yes",
    },
  ];
  const participantTestimonies: DosAppParticipantTestimony[] = [
    {
      decisionMade: "Keep meeting weekly and bring my sister along.",
      id: "demo-participant-testimony-naomi",
      meetingId: "demo-meeting-naomi-recent-1",
      nextStep: "Invite my sister to the Thursday study.",
      permissionToShare: true,
      personId: "demo-person-naomi-lee",
      publicDisplayName: null,
      status: "approved",
      story: "I grew up around church but never thought God had much to do with my week. Reading John together changed that. When my family started asking why I seemed different, I finally had something honest to say.",
      submittedAt: daysAgoIso(1, 19),
      submittedEmail: null,
      submittedName: "Naomi Lee",
      whatChanged: "I stopped hiding what I believe from my family.",
    },
  ];
  const assessmentResults: DosAppAssessmentResult[] = [
    {
      answers: {},
      assessmentTitle: "Marriage Assessment",
      assessmentType: "marriage-assessment",
      categoryScores: [
        { husbandScore: 42, maxScore: 50, name: "Connection", percentage: 82, score: 41, wifeScore: 40 },
        { husbandScore: 37, maxScore: 50, name: "Communication", percentage: 76, score: 38, wifeScore: 39 },
      ],
      completedAt: "2026-05-26T19:00:00-05:00",
      completedByEmail: null,
      completedByName: null,
      id: "demo-assessment-george-marriage",
      maxScore: 150,
      overallScore: 119,
      percentage: 79,
      personId: "demo-person-george-jenko",
      secondaryPersonId: null,
      source: "self",
      workspaceId: demoWorkspaceId,
    },
  ];
  const prayerRequests: DosAppData["prayerRequests"] = [
    {
      answerTestimony: null,
      answeredAt: null,
      category: "Ministry",
      createdAt: demoTimestamp,
      createdByPersonId: "demo-person-george-jenko",
      createdByUserId: null,
      fieldPersonId: "demo-person-tim-tran",
      followUpAt: "2026-07-12T09:00:00-05:00",
      gatheringId: "demo-group-2three2-gathering-1",
      groupId: "demo-group-2three2",
      id: "demo-prayer-2three2-tim",
      linkedPersonIds: ["demo-person-tim-tran"],
      meetingId: null,
      organizationId: null,
      personTags: ["Tim Tran", "2three2"],
      priority: "high",
      request: "Pray for strength and steady pursuit as Tim builds a weekly rhythm of Scripture, running, and prayer.",
      source: "dos_group",
      status: "active",
      title: "Strength and endurance",
      updatedAt: demoTimestamp,
      urgency: "important",
      visibility: "group_members",
      workspaceId: demoWorkspaceId,
    },
  ];
  const groups: DosAppData["groups"] = [
    {
      acceptingMembers: true,
      active: true,
      activityType: "running",
      audience: "men",
      capacity: 20,
      defaultLocation: "Lebanon Hills Trailhead, Eagan, MN",
      locationAddress: null,
      locationLabel: "Lebanon Hills Trailhead, Eagan, MN",
      description: "A men's discipleship group where we run together, pair up two-by-two, pray for one another, and pursue righteousness, faith, love, and peace.",
      gatherings: [
        {
          actingLeaderPersonId: null,
          attendance: [],
          completedAt: null,
          description: "Run together, pair up two-by-two, and pray along the trail.",
          endsAt: "2026-07-11T08:15:00-05:00",
          fruitSummary: null,
          id: "demo-group-2three2-gathering-1",
          linkedTableEventId: null,
          location: "Lebanon Hills Trailhead, Eagan, MN",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: null,
          sharedPrayerSummary: null,
          startsAt: "2026-07-11T07:00:00-05:00",
          startedAt: null,
          status: "scheduled",
          title: "Saturday Run & Prayer",
        },
        {
          actingLeaderPersonId: null,
          attendance: [],
          completedAt: null,
          description: "Run together, pair up two-by-two, and pray along the trail.",
          endsAt: "2026-07-18T08:15:00-05:00",
          fruitSummary: null,
          id: "demo-group-2three2-gathering-2",
          linkedTableEventId: null,
          location: "Lebanon Hills Trailhead, Eagan, MN",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: null,
          sharedPrayerSummary: null,
          startsAt: "2026-07-18T07:00:00-05:00",
          startedAt: null,
          status: "scheduled",
          title: "Saturday Run & Prayer",
        },
      ],
      id: "demo-group-2three2",
      imageUrl: null,
      leaderName: "George Jenko",
      leaderPersonId: "demo-person-george-jenko",
      memberCount: 2,
      recurrenceEffectiveDate: null,
      recurrenceEndDate: null,
      members: [
        {
          id: "demo-group-member-george",
          joinedAt: demoTimestamp,
          notes: null,
          permissions: { canLogGatherings: true, canManageGroup: true, canManagePeople: true },
          personId: "demo-person-george-jenko",
          personName: "George Jenko",
          role: "leader",
          status: "active",
          title: "Primary Leader",
        },
        {
          id: "demo-group-member-tim",
          joinedAt: demoTimestamp,
          notes: null,
          permissions: {},
          personId: "demo-person-tim-tran",
          personName: "Tim Tran",
          role: "member",
          status: "active",
          title: null,
        },
      ],
      name: "2three2",
      prayerRequests: prayerRequests.filter((request) => request.groupId === "demo-group-2three2"),
      primaryLeaderPersonId: "demo-person-george-jenko",
      resources: [
        {
          active: true,
          catalogResourceSlug: null,
          description: "Verse anchor for the 2three2 rhythm.",
          id: "demo-group-resource-2timothy",
          resourceType: "scripture",
          sortOrder: 10,
          title: "2 Timothy 2:22",
          url: null,
        },
      ],
      rhythmLabel: "Weekly · Saturday · 7:00 AM",
      scriptureReference: "2 Timothy 2:22",
      scriptureText: "Flee also youthful lusts; but pursue righteousness, faith, love, peace with those who call on the Lord out of a pure heart.",
      settings: {},
      sharedLeadershipEnabled: true,
      slug: "2three2",
      tagline: "Run. Pray. Pursue.",
      templateCategory: "activity",
      templateKey: "2three2_running_men",
      type: "running",
      visibility: "private",
    },
    {
      acceptingMembers: true,
      active: true,
      activityType: null,
      audience: "men",
      capacity: 12,
      defaultLocation: "Location varies",
      locationAddress: null,
      locationLabel: "Location varies",
      description: "A weekly gathering focused on Scripture, accountability, prayer, and helping men pursue Christ together.",
      gatherings: [
        {
          actingLeaderPersonId: null,
          attendance: [],
          completedAt: null,
          description: "Scripture, accountability, and prayer before the day begins.",
          endsAt: "2026-07-14T07:00:00-05:00",
          fruitSummary: null,
          id: "demo-group-tuesday-mens-gathering-1",
          linkedTableEventId: null,
          location: "Location varies",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: null,
          sharedPrayerSummary: null,
          startsAt: "2026-07-14T06:00:00-05:00",
          startedAt: null,
          status: "scheduled",
          title: "Tuesday Men's Group",
        },
        {
          actingLeaderPersonId: "demo-person-george-jenko",
          attendance: [
            {
              firstTimeGuest: false,
              gatheringId: "demo-group-tuesday-mens-gathering-0",
              id: "demo-group-tuesday-mens-gathering-0-attendance-george",
              notes: null,
              personId: "demo-person-george-jenko",
              personName: "George Jenko",
              status: "present",
            },
            {
              firstTimeGuest: false,
              gatheringId: "demo-group-tuesday-mens-gathering-0",
              id: "demo-group-tuesday-mens-gathering-0-attendance-tim",
              notes: "Shared how the promotion talk went at work.",
              personId: "demo-person-tim-tran",
              personName: "Tim Tran",
              status: "present",
            },
          ],
          completedAt: "2026-07-07T07:00:00-05:00",
          description: "Scripture, accountability, and prayer before the day begins.",
          endsAt: "2026-07-07T07:00:00-05:00",
          fruitSummary: null,
          id: "demo-group-tuesday-mens-gathering-0",
          linkedTableEventId: null,
          location: "Location varies",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: "Worked through 1 Peter 5 on humility under pressure.",
          sharedPrayerSummary: null,
          startsAt: "2026-07-07T06:00:00-05:00",
          startedAt: "2026-07-07T06:00:00-05:00",
          status: "completed",
          title: "Tuesday Men's Group",
        },
      ],
      id: "demo-group-tuesday-mens",
      imageUrl: null,
      leaderName: "George Jenko",
      leaderPersonId: "demo-person-george-jenko",
      memberCount: 2,
      recurrenceEffectiveDate: null,
      recurrenceEndDate: null,
      members: [
        {
          id: "demo-group-tuesday-member-george",
          joinedAt: demoTimestamp,
          notes: null,
          permissions: { canLogGatherings: true, canManageGroup: true, canManagePeople: true },
          personId: "demo-person-george-jenko",
          personName: "George Jenko",
          role: "leader",
          status: "active",
          title: "Primary Leader",
        },
        {
          id: "demo-group-tuesday-member-tim",
          joinedAt: demoTimestamp,
          notes: null,
          permissions: {},
          personId: "demo-person-tim-tran",
          personName: "Tim Tran",
          role: "member",
          status: "active",
          title: null,
        },
      ],
      name: "Tuesday Men's Group",
      prayerRequests: prayerRequests.filter((request) => request.groupId === "demo-group-tuesday-mens"),
      primaryLeaderPersonId: "demo-person-george-jenko",
      resources: [],
      rhythmLabel: "Weekly · Tuesday · 6:00 AM",
      scriptureReference: null,
      scriptureText: null,
      settings: {},
      sharedLeadershipEnabled: true,
      slug: "tuesday-mens-group",
      tagline: "Grow together.",
      templateCategory: "discipleship",
      templateKey: "mens_discipleship",
      type: "discipleship",
      visibility: "private",
    },
    {
      acceptingMembers: true,
      active: true,
      activityType: null,
      audience: "men",
      capacity: 12,
      defaultLocation: "Ryan's House",
      locationAddress: "9745 Oak Shore Dr, Lakeville, MN 55044",
      locationLabel: "Ryan's House",
      description: "An evening gathering where men encourage one another, study Scripture, pray together, and build authentic Christian community.",
      gatherings: [
        {
          actingLeaderPersonId: null,
          attendance: [],
          completedAt: null,
          description: "Study Scripture, pray together, and encourage one another.",
          endsAt: "2026-07-08T20:00:00-05:00",
          fruitSummary: null,
          id: "demo-group-wednesday-mens-gathering-1",
          linkedTableEventId: null,
          location: "Ryan's House",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: null,
          sharedPrayerSummary: null,
          startsAt: "2026-07-08T18:30:00-05:00",
          startedAt: null,
          status: "scheduled",
          title: "Wednesday Men's Group",
        },
      ],
      id: "demo-group-wednesday-mens",
      imageUrl: null,
      leaderName: "Caleb Rivera",
      leaderPersonId: "demo-person-caleb-rivera",
      memberCount: 3,
      recurrenceEffectiveDate: null,
      recurrenceEndDate: null,
      members: [
        {
          id: "demo-group-wednesday-member-caleb",
          joinedAt: demoTimestamp,
          // Demo identity states cover the four leader-visible conditions from
          // USA-170: linked account (Caleb), invitation expired (Tim), scoped
          // access active (Tanner). "Person only" is every member without a
          // memberAccess record, e.g. the Tuesday group members.
          memberAccess: {
            authLinked: true,
            invitation: "used",
            status: "verified",
            verifiedAt: demoTimestamp,
            verifiedEmail: "caleb.rivera@example.com",
            verifiedPhone: null,
          },
          notes: null,
          permissions: { canLogGatherings: true, canManageGroup: true, canManagePeople: true },
          personId: "demo-person-caleb-rivera",
          personName: "Caleb Rivera",
          role: "leader",
          status: "active",
          title: "Primary Leader",
        },
        {
          id: "demo-group-wednesday-member-tim",
          joinedAt: demoTimestamp,
          memberAccess: {
            authLinked: false,
            invitation: "expired",
            status: "invited",
            verifiedAt: null,
            verifiedEmail: null,
            verifiedPhone: null,
          },
          notes: null,
          permissions: {},
          personId: "demo-person-tim-tran",
          personName: "Tim Tran",
          role: "member",
          status: "active",
          title: null,
        },
        {
          id: "demo-group-wednesday-member-tanner",
          joinedAt: "2026-08-10T18:15:00-05:00",
          memberAccess: {
            authLinked: false,
            invitation: "used",
            status: "verified",
            verifiedAt: "2026-08-12T13:05:00-05:00",
            verifiedEmail: "tanner.kent@example.com",
            verifiedPhone: null,
          },
          notes: null,
          permissions: {},
          personId: "demo-person-tanner-kent",
          personName: "Tanner Kent",
          role: "member",
          status: "active",
          title: null,
        },
      ],
      name: "Wednesday Men's Group",
      prayerRequests: prayerRequests.filter((request) => request.groupId === "demo-group-wednesday-mens"),
      primaryLeaderPersonId: "demo-person-caleb-rivera",
      resources: [],
      rhythmLabel: "Weekly · Wednesday · 5:30 PM - 6:30 PM",
      scriptureReference: null,
      scriptureText: null,
      settings: {},
      sharedLeadershipEnabled: true,
      slug: "wednesday-mens-group",
      tagline: "Brotherhood. Prayer. Discipleship.",
      templateCategory: "discipleship",
      templateKey: "mens_discipleship",
      type: "discipleship",
      visibility: "private",
    },
    {
      acceptingMembers: true,
      active: true,
      activityType: null,
      audience: "women",
      capacity: 12,
      defaultLocation: "Fox Family home",
      description: "A women's study working through Scripture together, praying for one another, and inviting friends who are still exploring faith.",
      gatherings: [
        {
          actingLeaderPersonId: null,
          attendance: [
            {
              firstTimeGuest: false,
              gatheringId: "demo-group-thursday-womens-gathering-1",
              id: "demo-attendance-thursday-1-naomi",
              notes: "Shared about the conversation with her family.",
              personId: "demo-person-naomi-lee",
              personName: "Naomi Lee",
              status: "present",
            },
            {
              firstTimeGuest: false,
              gatheringId: "demo-group-thursday-womens-gathering-1",
              id: "demo-attendance-thursday-1-brooke",
              notes: null,
              personId: "demo-person-brooke-fox",
              personName: "Brooke Fox",
              status: "present",
            },
          ],
          completedAt: daysAgoIso(9, 20),
          description: "Working through the Gospel of John together.",
          endsAt: daysAgoIso(9, 20),
          fruitSummary: null,
          id: "demo-group-thursday-womens-gathering-1",
          linkedTableEventId: null,
          location: "Fox Family home",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: "Naomi asked the group to pray for her family.",
          sharedPrayerSummary: null,
          startsAt: daysAgoIso(9, 18),
          startedAt: daysAgoIso(9, 18),
          status: "completed",
          title: "Thursday Women's Study",
        },
        {
          actingLeaderPersonId: null,
          attendance: [],
          completedAt: null,
          description: "Working through the Gospel of John together.",
          endsAt: daysAgoIso(-5, 20),
          fruitSummary: null,
          id: "demo-group-thursday-womens-gathering-2",
          linkedTableEventId: null,
          location: "Fox Family home",
          ministryEventId: null,
          sharedFollowUp: null,
          sharedNotes: null,
          sharedPrayerSummary: null,
          startsAt: daysAgoIso(-5, 18),
          startedAt: null,
          status: "scheduled",
          title: "Thursday Women's Study",
        },
      ],
      id: "demo-group-thursday-womens",
      imageUrl: null,
      leaderName: "Brooke Fox",
      leaderPersonId: "demo-person-brooke-fox",
      locationAddress: null,
      locationLabel: "Fox Family home",
      memberCount: 2,
      members: [
        {
          id: "demo-group-member-thursday-brooke",
          joinedAt: demoTimestamp,
          notes: null,
          permissions: { canLogGatherings: true, canManageGroup: true, canManagePeople: true },
          personId: "demo-person-brooke-fox",
          personName: "Brooke Fox",
          role: "leader",
          status: "active",
          title: "Primary Leader",
        },
        {
          id: "demo-group-member-thursday-naomi",
          joinedAt: demoTimestamp,
          notes: null,
          permissions: {},
          personId: "demo-person-naomi-lee",
          personName: "Naomi Lee",
          role: "member",
          status: "active",
          title: null,
        },
      ],
      name: "Thursday Women's Study",
      prayerRequests: [],
      primaryLeaderPersonId: "demo-person-brooke-fox",
      recurrenceEffectiveDate: null,
      recurrenceEndDate: null,
      resources: [],
      rhythmLabel: "Weekly · Thursday · 6:00 PM - 8:00 PM",
      scriptureReference: null,
      scriptureText: null,
      settings: {},
      sharedLeadershipEnabled: false,
      slug: "thursday-womens-study",
      tagline: "Scripture. Prayer. Friendship.",
      templateCategory: "discipleship",
      templateKey: "womens_study",
      type: "study",
      visibility: "private",
    },
  ];
  const reminders: DosAppRelationshipReminder[] = [
    {
      googleSyncEnabled: false,
      googleSyncStatus: null,
      id: "demo-reminder-philip-followup",
      notes: "",
      personId: "demo-person-philip-saco",
      recurrence: "none",
      reminderDate: daysAgoIso(-12, 12),
      reminderType: "follow_up",
      title: "Ask how conversations with the men are going",
      updatedAt: demoTimestamp,
    },
    {
      googleSyncEnabled: true,
      googleSyncStatus: "pending",
      id: "demo-reminder-george-birthday",
      notes: "Send a note in the morning.",
      personId: "demo-person-george-jenko",
      recurrence: "yearly",
      reminderDate: "2026-06-11T12:00:00-05:00",
      reminderType: "birthday",
      title: null,
      updatedAt: demoTimestamp,
    },
    {
      googleSyncEnabled: false,
      googleSyncStatus: null,
      id: "demo-reminder-naomi-follow-up",
      notes: "She asked for prayer for peace and wisdom at home.",
      personId: "demo-person-naomi-lee",
      recurrence: "none",
      reminderDate: daysAgoIso(-2, 12),
      reminderType: "follow_up",
      title: "Ask how her family is doing",
      updatedAt: demoTimestamp,
    },
  ];

  const circles = withManualCircleOverride(
    buildFallbackCircleDataFromActivity({
      meetings: meetings.filter((meeting) => meeting.meetingStatus === "logged").map((meeting) => ({
        date: meeting.date,
        fieldPersonIds: meeting.fieldPersonIds,
      })),
      people: people.map((person) => ({
        engagementLevel: person.engagementLevel,
        id: person.id,
        lastActivityAt: person.lastActivityAt,
        name: person.name,
        relationshipType: person.relationshipType,
        status: person.status,
      })),
      workspaceId: demoWorkspaceId,
    }),
    "demo-person-naomi-lee",
    "twelve",
    "Pinned to My 12 for workspace stewardship while this relationship is confirmed.",
  );

  return {
    accountabilityCheckInCommitments: [],
    accountabilityCheckIns: [
      {
        checkInDate: "2026-08-11",
        createdAt: "2026-08-11T06:20:00-05:00",
        createdByUserId: null,
        durationMinutes: 15,
        followUp: null,
        generalUpdate: "Consistent quiet time most days this week; missed Tuesday.",
        id: "demo-accountability-check-in-george-quiet-time-1",
        personId: "demo-person-george-jenko",
        prayerNeeds: null,
        scheduleId: "demo-accountability-schedule-george-quiet-time",
        struggles: null,
        updatedAt: null,
        wins: "Started journaling through Psalms.",
        workspaceId: demoWorkspaceId,
      },
    ],
    accountabilitySchedules: [
      {
        createdAt: daysAgoIso(6),
        createdByUserId: null,
        dayOfWeek: null,
        frequency: "one_time",
        id: "demo-accountability-philip-reading",
        nextCheckIn: daysAgoIso(-24).slice(0, 10),
        personId: "demo-person-philip-saco",
        scheduledTime: null,
        startDate: daysAgoIso(6).slice(0, 10),
        status: "active",
        title: "Read assigned material",
        updatedAt: null,
        workspaceId: demoWorkspaceId,
      },
      {
        createdAt: daysAgoIso(6),
        createdByUserId: null,
        dayOfWeek: null,
        frequency: "one_time",
        id: "demo-accountability-philip-disciple",
        nextCheckIn: daysAgoIso(-24).slice(0, 10),
        personId: "demo-person-philip-saco",
        scheduledTime: null,
        startDate: daysAgoIso(6).slice(0, 10),
        status: "active",
        title: "Begin discipling other men",
        updatedAt: null,
        workspaceId: demoWorkspaceId,
      },
      {
        createdAt: demoTimestamp,
        createdByUserId: null,
        dayOfWeek: 1,
        frequency: "weekly",
        id: "demo-accountability-schedule-george-quiet-time",
        nextCheckIn: "2026-08-18",
        personId: "demo-person-george-jenko",
        scheduledTime: null,
        startDate: "2026-06-01",
        status: "active",
        title: "Quiet Time With God",
        updatedAt: null,
        workspaceId: demoWorkspaceId,
      },
      {
        createdAt: demoTimestamp,
        createdByUserId: null,
        dayOfWeek: 1,
        frequency: "weekly",
        id: "demo-accountability-schedule-george-purity",
        nextCheckIn: "2026-08-18",
        personId: "demo-person-george-jenko",
        scheduledTime: null,
        startDate: "2026-06-01",
        status: "active",
        title: "Purity",
        updatedAt: null,
        workspaceId: demoWorkspaceId,
      },
      {
        createdAt: daysAgoIso(14),
        createdByUserId: null,
        dayOfWeek: 4,
        frequency: "weekly",
        id: "demo-accountability-schedule-naomi-scripture",
        nextCheckIn: daysAgoIso(-1).slice(0, 10),
        personId: "demo-person-naomi-lee",
        scheduledTime: null,
        startDate: daysAgoIso(14).slice(0, 10),
        status: "active",
        title: "Daily Scripture reading",
        updatedAt: null,
        workspaceId: demoWorkspaceId,
      },
    ],
    assessmentResults,
    calendarConnection: {
      calendarId: "primary",
      connected: true,
      connectedAt: demoTimestamp,
      googleAccountEmail: "ryan@example.com",
      googleConfigured: true,
      lastSyncedAt: demoTimestamp,
    },
    circles,
    /* One-time Accountability now lands here rather than in schedules, so the
       demo Person shows both halves of the one section: a measurable goal with
       real progress, and an ordinary dated goal with none. */
    commitments: [
      {
        assignedDate: daysAgoIso(6).slice(0, 10),
        category: null,
        completedDate: null,
        createdAt: daysAgoIso(6),
        createdByUserId: null,
        description: null,
        id: "demo-commitment-philip-multiply",
        personId: "demo-person-philip-saco",
        status: "active",
        targetCount: 3,
        targetKind: "people" as const,
        targetDate: daysAgoIso(-30).slice(0, 10),
        title: "Begin discipling 3 men",
        updatedAt: null,
        updates: [
          {
            commitmentId: "demo-commitment-philip-multiply",
            createdAt: daysAgoIso(2),
            createdByUserId: null,
            id: "demo-commitment-update-philip-marcus",
            personId: "demo-person-philip-saco",
            progressNote: "Started meeting with Marcus on Tuesdays.",
            progressAmount: null,
            progressState: "in_progress",
            subjectPersonId: null,
            subjectPersonName: "Marcus",
            updateDate: daysAgoIso(2).slice(0, 10),
            workspaceId: demoWorkspaceId,
          },
          /* A second update about the same man. He is still one confirmed
             person, dated from when he started rather than when he was last
             mentioned. */
          {
            commitmentId: "demo-commitment-philip-multiply",
            createdAt: daysAgoIso(1),
            createdByUserId: null,
            id: "demo-commitment-update-philip-marcus-2",
            personId: "demo-person-philip-saco",
            progressNote: "Marcus is bringing a friend next week.",
            progressAmount: null,
            progressState: null,
            subjectPersonId: null,
            subjectPersonName: "marcus",
            updateDate: daysAgoIso(1).slice(0, 10),
            workspaceId: demoWorkspaceId,
          },
        ],
        workspaceId: demoWorkspaceId,
      },
      {
        assignedDate: daysAgoIso(3).slice(0, 10),
        category: null,
        completedDate: null,
        createdAt: daysAgoIso(3),
        createdByUserId: null,
        description: null,
        id: "demo-commitment-philip-john",
        personId: "demo-person-philip-saco",
        status: "active",
        targetCount: null,
        targetKind: null,
        targetDate: daysAgoIso(-3).slice(0, 10),
        title: "Read John 4-6",
        updatedAt: null,
        updates: [],
        workspaceId: demoWorkspaceId,
      },
    ],
    externalCalendarEvents: [],
    featureFlags: {
      commitmentsAccountability: true,
      engagementLevels: false,
      groupsSimplifiedV2: true,
    },
    fruit,
    fruitEvents,
    groups,
    guidedResourceProgress: [
      {
        actionStep: "Told my accountability partner I'm choosing obedience over admiration this week.",
        assignmentId: "demo-assignment-discipleship-tim",
        completedAt: demoTimestamp,
        createdAt: demoTimestamp,
        createdByUserId: null,
        id: "demo-progress-discipleship-week-1",
        personId: "demo-person-tim-tran",
        prayerFocus: "Ask for an undivided heart this week.",
        reflection: "I've been admiring Jesus from a distance instead of actually following him.",
        resourceSlug: "marks-of-discipleship",
        sessionId: "week-1",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
      {
        actionStep: "Start reading John with someone in my family.",
        assignmentId: "demo-assignment-discipleship-naomi",
        completedAt: daysAgoIso(12),
        createdAt: daysAgoIso(12),
        createdByUserId: null,
        id: "demo-progress-naomi-week-1",
        personId: "demo-person-naomi-lee",
        prayerFocus: "Courage to talk about faith at home.",
        reflection: "Following Jesus has to show up in how I treat my family.",
        resourceSlug: "marks-of-discipleship",
        sessionId: "week-1",
        updatedAt: daysAgoIso(12),
        workspaceId: demoWorkspaceId,
      },
      {
        actionStep: "Keep a daily reading rhythm this week.",
        assignmentId: "demo-assignment-discipleship-naomi",
        completedAt: daysAgoIso(5),
        createdAt: daysAgoIso(5),
        createdByUserId: null,
        id: "demo-progress-naomi-week-2",
        personId: "demo-person-naomi-lee",
        prayerFocus: "Peace and wisdom with her family.",
        reflection: "Obedience is easier when I remember I'm loved first.",
        resourceSlug: "marks-of-discipleship",
        sessionId: "week-2",
        updatedAt: daysAgoIso(5),
        workspaceId: demoWorkspaceId,
      },
      // Kept from main: Tanner's Group Journey progress for USA-170 QA.
      {
        actionStep: "Asked Ryan to check in next week after I read the second session.",
        assignmentId: "demo-assignment-wednesday-discipleship-tanner",
        completedAt: demoTimestamp,
        createdAt: demoTimestamp,
        createdByUserId: null,
        id: "demo-progress-wednesday-tanner-discipleship-week-1",
        personId: "demo-person-tanner-kent",
        prayerFocus: "Keep my obedience simple and steady.",
        reflection: "I want to follow Jesus in practice, not just understand the idea of discipleship.",
        resourceSlug: "marks-of-discipleship",
        sessionId: "week-1",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
    ],
    householdMembers: [
      {
        displayName: "Ryan Fox",
        id: "demo-household-member-ryan",
        inviteEmail: "ryan@example.com",
        isPublic: true,
        linked: true,
        relationship: "owner",
        roleTitle: "Missionary",
        status: "active",
      },
      {
        displayName: "Brooke Fox",
        id: "demo-household-member-brooke",
        inviteEmail: "brooke@example.com",
        isPublic: true,
        linked: false,
        relationship: "spouse",
        roleTitle: "Missionary",
        status: "active",
      },
    ],
    leaderReflections,
    meetings,
    organizations: [
      {
        id: "independent",
        name: "Independent DOS",
        profileStatus: null,
        publicProfileHref: null,
        publicProfileLive: false,
        slug: null,
        status: "active",
        type: "independent",
      },
      {
        id: "demo-usam-organization",
        name: "USA Missionaries",
        profileStatus: "published",
        publicProfileHref: "/missionaries/ryan-brooke-fox",
        publicProfileLive: true,
        slug: "usa-missionaries",
        status: "active",
        type: "usam",
      },
      {
        id: "river-valley-church",
        name: "River Valley Church",
        profileStatus: null,
        publicProfileHref: null,
        publicProfileLive: false,
        slug: "river-valley-church",
        status: "active",
        type: "church",
      },
    ],
    participantReviews,
    participantTestimonies,
    people,
    prayerLogs: [],
    prayerPartners: [
      {
        city: "Tulsa",
          email: "brooke.fox@example.com",
          fieldPersonId: "demo-person-brooke",
          howHeard: "invited_by_me",
          id: "demo-prayer-partner-brooke",
          joinedAt: demoTimestamp,
          name: "Brooke Fox",
          notes: "Prays over family and field rhythm.",
          phone: "918-555-0182",
          prayerTeam: "household_family",
          region: null,
          relationshipContext: "family",
          source: "dos",
        state: "OK",
        status: "active",
        updatedAt: demoTimestamp,
      },
    ],
    prayerRequests,
    myRecord: {
      assessmentResults: [
        {
          answers: {
            "connect-with-god": 8,
            "respect-love": 9,
            "time-together": 7,
            trust: 8,
            understood: 7,
          },
          assessmentName: "Marriage Assessment",
          assessmentResourceId: "relationship-marriage-assessment",
          assessmentSlug: "marriage-assessment",
          categoryScores: [
            { id: "respect-love", maxScore: 10, percentage: 90, score: 9, title: "How respected or loved do you feel in the relationship?" },
            { id: "connect-with-god", maxScore: 10, percentage: 80, score: 8, title: "How well do I help you connect with God?" },
          ],
          completedAt: demoTimestamp,
          createdAt: demoTimestamp,
          id: "demo-my-record-assessment",
          maxScore: 150,
          overallScore: 39,
          percentage: 26,
          updatedAt: demoTimestamp,
          visibility: "private",
        },
      ],
      externalAssessmentResults: [
        {
          assessmentName: "Working Genius",
          attachmentBucket: null,
          attachmentContentType: null,
          attachmentFileName: null,
          attachmentPath: null,
          attachmentUploadedAt: null,
          attachmentUrl: null,
          category: "Working Genius",
          createdAt: demoTimestamp,
          dateTaken: "2026-06-28",
          id: "demo-my-record-external-assessment",
          notes: "Use this for team design and weekly planning conversations.",
          officialAssessmentUrl: "https://www.workinggenius.com/",
          resultType: "Galvanizing / Enablement",
          retakeReminderDate: "2027-06-28",
          scoresDetails: "Manual summary entered after taking the assessment externally.",
          shareEligible: false,
          shortSummary: "Manual summary entered after taking the assessment externally.",
          status: "completed",
          topStrengths: ["Galvanizing", "Enablement", "Tenacity"],
          updatedAt: demoTimestamp,
          visibility: "private",
        },
      ],
      createdAt: demoTimestamp,
      currentSeasonFocus: "Abide before activity.",
      displayName: "Ryan Fox",
      id: "demo-my-record",
      journalEntries: [],
      learningBooks: [
        {
          author: "Dallas Willard",
          chapterNotes: [
            {
              chapterLabel: "Chapter 1",
              chapterNumber: 1,
              createdAt: demoTimestamp,
              highlightImageBucket: null,
              highlightImageContentType: null,
              highlightImageFileName: null,
              highlightImagePath: null,
              highlightImageUploadedAt: null,
              highlightImageUrl: null,
              highlights: "The kingdom of God is available now.",
              id: "demo-my-record-learning-chapter",
              notes: "Capture highlights and application without changing Field activity.",
              personalApplication: "Practice slower obedience before activity.",
              updatedAt: demoTimestamp,
            },
          ],
          createdAt: demoTimestamp,
          finalSummary: "A private personal summary will live here after finishing the book.",
          finishedOn: null,
          id: "demo-my-record-learning-book",
          personalApplication: "Bring reading into prayer and mentor conversations.",
          shareEligible: false,
          startedOn: "2026-07-01",
          status: "reading",
          title: "The Divine Conspiracy",
          updatedAt: demoTimestamp,
          visibility: "private",
        },
      ],
      lifePlan: null,
      mentorMeetings: [],
      mentorRelationships: [],
      prayerLogs: [],
      propheticWords: [
        {
          confirmations: "Confirmed through mentor counsel and John 15.",
          context: "Prayer night",
          createdAt: demoTimestamp,
          dateReceived: "2026-07-01",
          givenBy: "Leif Hetland",
          id: "demo-my-record-prophetic-word",
          notes: "Testing this with Brooke and mentors.",
          scriptureReferences: ["John 15", "Isaiah 61"],
          status: "testing",
          tags: ["Abide", "Family", "Calling"],
          updatedAt: demoTimestamp,
          wordText: "Abide before activity and build from rest.",
        },
      ],
      updatedAt: demoTimestamp,
      userId: "demo-user-ryan",
      workspaceId: demoWorkspaceId,
    },
    reminders,
    resourceAssignments: [
      {
        assignmentContext: "group",
        assignedByUserId: "demo-user-ryan",
        completedAt: null,
        createdAt: demoTimestamp,
        dueDate: null,
        followUpCadence: "weekly",
        id: "demo-assignment-discipleship-tim",
        linkedCommitmentId: null,
        pausedAt: null,
        personId: "demo-person-tim-tran",
        personalMessage: "Walk through this six-week discipleship resource and capture one reflection after each session.",
        resourceSlug: "marks-of-discipleship",
        sharingLevel: "leader_progress",
        sourceGroupId: "demo-group-2three2",
        startDate: "2026-07-15",
        status: "in_progress",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
      {
        assignmentContext: "person",
        assignedByUserId: "demo-user-ryan",
        completedAt: null,
        createdAt: daysAgoIso(16),
        dueDate: daysAgoIso(-33).slice(0, 10),
        followUpCadence: "weekly",
        id: "demo-assignment-discipleship-naomi",
        linkedCommitmentId: null,
        pausedAt: null,
        personId: "demo-person-naomi-lee",
        personalMessage: "Walking through Discipleship together over the next seven weeks.",
        resourceSlug: "marks-of-discipleship",
        sharingLevel: "leader_progress",
        sourceGroupId: null,
        startDate: daysAgoIso(16).slice(0, 10),
        status: "in_progress",
        updatedAt: daysAgoIso(5),
        workspaceId: demoWorkspaceId,
      },
      {
        assignmentContext: "group",
        assignedByUserId: "demo-user-ryan",
        completedAt: null,
        createdAt: demoTimestamp,
        dueDate: null,
        followUpCadence: "weekly",
        id: "demo-assignment-wednesday-discipleship-tanner",
        linkedCommitmentId: null,
        pausedAt: null,
        personId: "demo-person-tanner-kent",
        personalMessage: "Walk through Discipleship together during the Wednesday Men's Group study period.",
        resourceSlug: "marks-of-discipleship",
        sharingLevel: "leader_progress",
        sourceGroupId: "demo-group-wednesday-mens",
        startDate: "2026-08-12",
        status: "in_progress",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
      {
        assignmentContext: "group",
        assignedByUserId: "demo-user-ryan",
        completedAt: null,
        createdAt: demoTimestamp,
        dueDate: null,
        followUpCadence: "weekly",
        id: "demo-assignment-wednesday-discipleship-caleb",
        linkedCommitmentId: null,
        pausedAt: null,
        personId: "demo-person-caleb-rivera",
        personalMessage: "Walk through Discipleship together during the Wednesday Men's Group study period.",
        resourceSlug: "marks-of-discipleship",
        sharingLevel: "leader_progress",
        sourceGroupId: "demo-group-wednesday-mens",
        startDate: "2026-08-12",
        status: "not_started",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
      {
        assignmentContext: "group",
        assignedByUserId: "demo-user-ryan",
        completedAt: null,
        createdAt: demoTimestamp,
        dueDate: null,
        followUpCadence: "weekly",
        id: "demo-assignment-wednesday-discipleship-tim",
        linkedCommitmentId: null,
        pausedAt: null,
        personId: "demo-person-tim-tran",
        personalMessage: "Walk through Discipleship together during the Wednesday Men's Group study period.",
        resourceSlug: "marks-of-discipleship",
        sharingLevel: "leader_progress",
        sourceGroupId: "demo-group-wednesday-mens",
        startDate: "2026-08-12",
        status: "not_started",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
      {
        assignmentContext: "group",
        assignedByUserId: "demo-user-ryan",
        completedAt: null,
        createdAt: demoTimestamp,
        dueDate: null,
        followUpCadence: "due_only",
        id: "demo-assignment-wednesday-nt-sprint-tim",
        linkedCommitmentId: null,
        pausedAt: null,
        personId: "demo-person-tim-tran",
        personalMessage: "Read through the New Testament sprint at your own pace.",
        resourceSlug: "new-testament-14-days",
        sharingLevel: "leader_progress",
        sourceGroupId: "demo-group-wednesday-mens",
        startDate: "2026-07-17",
        status: "not_started",
        updatedAt: demoTimestamp,
        workspaceId: demoWorkspaceId,
      },
    ],
    tableInvitations: [],
    usamApplication: {
      applicationId: "demo-usam-application",
      appliedAt: demoTimestamp,
      assignedAdminEmail: "admin@usamissionaries.org",
      organizationId: "demo-usam-organization",
      organizationName: "USA Missionaries",
      profileStatus: "published",
      publicProfileHref: "/missionaries/ryan-brooke-fox",
      publicProfileLive: true,
      reviewedAt: demoTimestamp,
      status: "active",
    },
    stats: {
      approvedFruit: fruit.filter((item) => item.status === "approved").length,
      connectionsCount: meetings.filter((meeting) => meeting.source === "connection").length,
      fruitCount: fruit.length,
      meetingsCount: meetings.filter((meeting) => meeting.meetingStatus === "logged").length,
      peopleCount: people.length,
      relationshipStewardship: relationshipModelCounts(people.map((person) => ({
        discipleshipStage: person.discipleshipStage,
        relationshipContext: person.relationshipContext,
        relationshipType: normalizeRelationshipType(person.relationshipType, person.roleInMyLife, person.status),
        roleInMyLife: person.roleInMyLife,
      }))),
    },
    workspace: {
      displayName: "Fox Family",
      greetingName: "Ryan",
      id: demoWorkspaceId,
      isPreview: true,
      isUsamWorkspace: true,
      organizationName: "USA Missionaries",
      profileImageUrl: null,
      publicProfileHref: "/missionaries/ryan-brooke-fox",
      shortMission: "DOS blue mobile demo preview.",
      showPrayerTeamCount: true,
      slug: "dos-preview",
      stateName: "Minnesota",
      userEmail: "ryan@foxfamily.org",
      userFullName: "Ryan Fox",
      userPhone: "(555) 013-1420",
    },
  };
}

export default async function DosAppPreviewPage({
  searchParams,
}: {
  searchParams: Promise<{ demo?: string; gallery?: string; workspace?: string }>;
}) {
  if (!isDemoPreviewRouteEnabled) {
    redirect("/dos");
  }

  const params = await searchParams;

  if (params.demo !== demoAccessToken) {
    return <LockedPreviewScreen />;
  }

  // USA-215: the shared primitives in isolation, behind the same token, for
  // visual regression and review. Synthetic content only.
  if (params.gallery === "primitives") {
    return <PrimitivesGallery />;
  }

  return <DosMvpAppClient data={buildDosPreviewDemoData()} />;
}
