/**
 * Deterministic error codes for the minimal automation replacement.
 *
 * Every refusal is a named code so callers, logs, and tests agree on meaning.
 * Codes are stable identifiers — do not renumber or reword them casually.
 */

export const ERROR_CODES = Object.freeze({
  // Configuration
  CONFIG_MISSING: "CONFIG_MISSING",
  CONFIG_MALFORMED: "CONFIG_MALFORMED",
  CONFIG_INVALID_FIELD: "CONFIG_INVALID_FIELD",

  // Linear live reads
  LINEAR_AUTH_MISSING: "LINEAR_AUTH_MISSING",
  LINEAR_QUERY_FAILED: "LINEAR_QUERY_FAILED",
  LINEAR_ISSUE_NOT_FOUND: "LINEAR_ISSUE_NOT_FOUND",
  LINEAR_STATE_NOT_FOUND: "LINEAR_STATE_NOT_FOUND",

  // Repository resolution (fail-closed)
  REPO_UNRESOLVED: "REPO_UNRESOLVED",
  REPO_BARE_NAME: "REPO_BARE_NAME",
  REPO_LOCAL_PATH_MISSING: "REPO_LOCAL_PATH_MISSING",

  // Issue eligibility
  ISSUE_NOT_READY: "ISSUE_NOT_READY",
  ISSUE_TERMINAL: "ISSUE_TERMINAL",
  ISSUE_ARCHIVED: "ISSUE_ARCHIVED",
  APPLICATION_MISSING: "APPLICATION_MISSING",
  APPLICATION_AMBIGUOUS: "APPLICATION_AMBIGUOUS",
  RUNNER_MISSING: "RUNNER_MISSING",
  RUNNER_AMBIGUOUS: "RUNNER_AMBIGUOUS",
  ACCEPTANCE_CRITERIA_MISSING: "ACCEPTANCE_CRITERIA_MISSING",

  // Capacity
  WIP_LIMIT_REACHED: "WIP_LIMIT_REACHED",
  REVIEW_CAP_REACHED: "REVIEW_CAP_REACHED",

  // Claiming
  CLAIM_CONFLICT: "CLAIM_CONFLICT",
  DUPLICATE_SESSION: "DUPLICATE_SESSION",

  // Cooldown (USA-68)
  RUNNER_COOLING_DOWN: "RUNNER_COOLING_DOWN",

  // Repository writer guard
  REPOSITORY_WRITER_ACTIVE: "REPOSITORY_WRITER_ACTIVE",
  REPOSITORY_MANUAL_ACTIVITY: "REPOSITORY_MANUAL_ACTIVITY",

  // Claude bridge
  CLAUDE_MENTION_MISSING: "CLAUDE_MENTION_MISSING",
  CLAUDE_ALREADY_HANDLED: "CLAUDE_ALREADY_HANDLED",
  CLAUDE_RUN_FAILED: "CLAUDE_RUN_FAILED",

  // Janitor
  WORKTREE_OUTSIDE_ALLOWLIST: "WORKTREE_OUTSIDE_ALLOWLIST",
  WORKTREE_DIRTY: "WORKTREE_DIRTY",
  WORKTREE_UNTRACKED: "WORKTREE_UNTRACKED",
  WORKTREE_UNPUSHED: "WORKTREE_UNPUSHED",
  WORKTREE_PR_OPEN: "WORKTREE_PR_OPEN",
  WORKTREE_ISSUE_ACTIVE: "WORKTREE_ISSUE_ACTIVE",
  WORKTREE_PATH_TRAVERSAL: "WORKTREE_PATH_TRAVERSAL",
  WORKTREE_PROTECTED_PATH: "WORKTREE_PROTECTED_PATH",

  // Backup
  BACKUP_DB_PASSWORD_MISSING: "BACKUP_DB_PASSWORD_MISSING",
  BACKUP_PASSPHRASE_MISSING: "BACKUP_PASSPHRASE_MISSING",
  BACKUP_OFFSITE_MISSING: "BACKUP_OFFSITE_MISSING",
  BACKUP_SCRIPT_MISSING: "BACKUP_SCRIPT_MISSING",
  BACKUP_ALREADY_RUNNING: "BACKUP_ALREADY_RUNNING",
  BACKUP_INCOMPLETE: "BACKUP_INCOMPLETE",
});

export class AutomationError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "AutomationError";
    this.code = code;
    this.details = details;
  }
  toJSON() {
    return { code: this.code, message: this.message, details: this.details };
  }
}

export function isKnownCode(code) {
  return Object.prototype.hasOwnProperty.call(ERROR_CODES, code);
}
