-- Rollback: put the September issue back the way it was.
--
-- Restores the row from revision 1 (Version A) if it is there, then drops what
-- this migration added. Revision history goes with the table, so export it
-- first if any of it matters.
--
-- Generated by scripts/september-newsletter-emit-migration.mjs. Do not hand-edit.

update public.communication_newsletters n
set
  title = r.snapshot ->> 'title',
  subject = r.snapshot ->> 'subject',
  preheader = r.snapshot ->> 'preheader',
  summary = r.snapshot ->> 'summary',
  sections = coalesce(r.snapshot -> 'sections', '[]'::jsonb),
  updated_at = now(),
  updated_by_email = 'rollback:20260917214500'
from public.communication_newsletter_revisions r
where r.newsletter_id = n.id
  and r.revision = 1
  and n.slug = 'q2-q3-2026-field-update';

drop table if exists public.communication_newsletter_revisions;

alter table public.communication_newsletters
  drop column if exists template,
  drop column if exists postal_address;
