-- September 2026 issue: the Operations record becomes the source of truth.
--
-- Until now the September issue rendered from a TypeScript module
-- (src/lib/communications/september-2026.ts) that render.ts selected by slug, so
-- its copy could only be changed by a developer and a deploy, and the record's
-- own body and sections were ignored. This migration moves the issue's content
-- onto the record and adds what a real review workflow needs:
--
--   * postal_address, so CAN-SPAM's physical address has a source at all. The
--     send-readiness check now blocks on it.
--   * template, so an issue names the renderer that draws it.
--   * communication_newsletter_revisions, so every edit is recoverable.
--
-- Version A is preserved twice over: the TypeScript module is untouched in the
-- repository, and the row as it stands right now is written into the revisions
-- table as revision 1 BEFORE anything is overwritten.
--
-- The featured testimony is deliberately absent. The sharing permission on
-- Planning Center form 1115723, submission 45980998 has not been verified, so
-- the story section is seeded hidden and carries no copy.
--
-- Generated by scripts/september-newsletter-emit-migration.mjs. Do not hand-edit.

alter table public.communication_newsletters
  add column if not exists postal_address text,
  add column if not exists template text;

comment on column public.communication_newsletters.postal_address is
  'CAN-SPAM physical mailing address. Null renders nothing and blocks sending.';
comment on column public.communication_newsletters.template is
  'Renderer for this issue: ''sections'' (default) or ''ecosystem''.';

create table if not exists public.communication_newsletter_revisions (
  id uuid primary key default gen_random_uuid(),
  newsletter_id uuid not null references public.communication_newsletters (id) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  summary text,
  created_at timestamptz not null default now(),
  created_by_email text not null,
  unique (newsletter_id, revision)
);

create index if not exists communication_newsletter_revisions_newsletter_idx
  on public.communication_newsletter_revisions (newsletter_id, revision desc);

alter table public.communication_newsletter_revisions enable row level security;

-- Service role only, matching the rest of the communications tables: every
-- reader and writer goes through the Operations server actions.
drop policy if exists communication_newsletter_revisions_service_role
  on public.communication_newsletter_revisions;
create policy communication_newsletter_revisions_service_role
  on public.communication_newsletter_revisions
  for all to service_role using (true) with check (true);

-- Revision 1: the row exactly as it is today, before this migration edits it.
insert into public.communication_newsletter_revisions
  (newsletter_id, revision, snapshot, summary, created_by_email)
select
  n.id,
  1,
  to_jsonb(n),
  'Version A, captured before the September issue moved onto its record.',
  'migration:20260917214500'
from public.communication_newsletters n
where n.slug = 'q2-q3-2026-field-update'
on conflict (newsletter_id, revision) do nothing;

-- The issue's content, as structured sections.
update public.communication_newsletters
set
  template = 'ecosystem',
  subject = 'There''s a Lot We''ve Been Wanting to Share',
  title = 'There''s a Lot We''ve Been Wanting to Share',
  preheader = 'Conversations with couples exploring the mission, what happened around a table, and the tool we are preparing.',
  summary = 'Conversations with couples exploring the mission, what happened around a table, and the tool we are preparing.',
  sections = '[
  {
    "body": "Three parts of one mission: the people we are gathering and preparing, what disciple making actually looks like around a table, and the tool being built to help it keep going.",
    "brand": "usam",
    "eyebrow": "Field Update // September 2026",
    "heading": "There''s a lot\nwe''ve been wanting\nto share",
    "hidden": false,
    "key": "header",
    "position": 0,
    "tagline": "Q2 / Q3 2026",
    "type": "header"
  },
  {
    "body": "There is a lot we have been wanting to share with you.\n\nOver these past months the Lord has been bringing real clarity to how this ministry fits together. We have been meeting people, gathering around tables, walking with men in discipleship, and building a tool to help that work continue.\n\nAll of it sits under one mission: USA Missionaries exists to locate, train, and deploy disciple makers across America. Here is what that looks like right now, and where we believe the Lord is leading next.",
    "brand": "usam",
    "heading": "Hi {{first_name}},",
    "hidden": false,
    "key": "opening",
    "position": 1,
    "type": "letter"
  },
  {
    "body": "USA Missionaries is the home for all of this. It is where the people, the training, and the sending live.\n\nAs we have shared the vision, we have begun conversations with several couples who are exploring what it could look like to join us. We are listening, praying, and taking time to know each other well. Nothing is being announced yet, and we are not rushing it. We are simply encouraged by the people God keeps bringing into these conversations.\n\nWe also rebuilt the website so the mission explains itself: locating, training, and deploying disciple makers across America.",
    "brand": "usam",
    "cta": {
      "label": "Explore USA Missionaries",
      "url": "https://usamissionaries.org"
    },
    "eyebrow": "The Covering",
    "heading": "The mission is\ntaking shape.",
    "hidden": false,
    "index": "01",
    "key": "usam-covering",
    "position": 2,
    "type": "pillar"
  },
  {
    "body": "Kitchen Table Gospel is the model, and it is not complicated. Real homes. Real tables. A meal, an open Bible, honest conversation, and prayer out loud.\n\nWhat makes it discipleship is not the evening itself. It is what keeps going afterward.",
    "brand": "ktg",
    "eyebrow": "The Model in Action",
    "heading": "What begins at a table\ncan keep growing.",
    "hidden": false,
    "image": {
      "alt": "Four friends gathered around a wooden table with an open Bible and the USA Missionaries vision binder.",
      "caption": "Kitchen Table Gospel // Minnesota",
      "url": "/images/email/september-2026/kitchen-table-01.jpg"
    },
    "index": "02",
    "key": "ktg-model",
    "position": 3,
    "type": "pillar"
  },
  {
    "body": "",
    "brand": "ktg",
    "eyebrow": "From the Table",
    "heading": "One evening,\nand what came after.",
    "hidden": true,
    "key": "ktg-story",
    "position": 4,
    "type": "story"
  },
  {
    "body": "Two men''s groups are also meeting consistently. They open Scripture together, pray, build real accountability, and keep walking through actual life with one another.\n\nIt is ordinary and it is working.",
    "brand": "ktg",
    "heading": "Men are gathering.",
    "hidden": false,
    "image": {
      "alt": "Six men from the USA Missionaries men''s discipleship group standing together outside, one holding a Bible.",
      "caption": "Men''s discipleship // Two groups meeting weekly",
      "url": "/images/email/september-2026/group-prayer-01.jpg"
    },
    "key": "ktg-men",
    "position": 5,
    "tagline": "2three2 — Run. Pray. Pursue.",
    "type": "feature"
  },
  {
    "body": "Invite someone in. Open Scripture together. Pray out loud, even if it is short. Then follow up during the week.\n\nThat is the whole model, and it is the one thing we would ask you to try.",
    "brand": "ktg",
    "cta": {
      "label": "Explore Kitchen Table Gospel",
      "url": "https://kitchentablegospel.org"
    },
    "heading": "Your table is enough.",
    "hidden": false,
    "key": "ktg-invitation",
    "position": 6,
    "tagline": "Gather. Learn. Confess. Encourage. Multiply.",
    "type": "invitation"
  },
  {
    "body": "We are getting close to a broader launch of the Discipleship Operating System. It has been in limited use while we build it, shaped by the very work you have just read about.\n\nIt is made to help disciple makers carry the people, the prayers, and the next steps they promised, so discipleship keeps going between the gatherings.\n\nTechnology cannot replace a conversation, a prayer, or a relationship. We only hope it makes it easier to keep showing up for someone, and to help them do the same for someone else.",
    "brand": "dos",
    "cta": {
      "label": "Request Information",
      "url": "https://discipleshipoperatingsystem.com"
    },
    "eyebrow": "The Tool Being Prepared",
    "heading": "Helping discipleship\ncontinue.",
    "hidden": false,
    "index": "03",
    "key": "dos-tool",
    "position": 7,
    "type": "pillar"
  },
  {
    "body": "Three parts, one mission. Gather and prepare people, show what disciple making actually looks like, and help it keep multiplying. That is all USA Missionaries is trying to do.\n\nThank you for praying for us, for encouraging us, and for partnering with this work. Would you pray for the couples we are talking with, for the people around these tables, for the two men''s groups, and for the preparation ahead of a broader DOS launch?",
    "brand": "usam",
    "heading": "We believe this is only the beginning.",
    "hidden": false,
    "key": "closing",
    "position": 8,
    "tagline": "Ryan & Brooke",
    "type": "closing"
  }
]'::jsonb,
  updated_at = now(),
  updated_by_email = 'migration:20260917214500'
where slug = 'q2-q3-2026-field-update';

-- Deliberately untouched: status, planned_send_at, ready_at, last_test_sent_at,
-- approved_at, approved_by_email, sent_at. The passed September 15 date is left
-- as it is rather than replaced with an invented one, the issue stays
-- unapproved, and nothing here enables a send.
