-- LEDGER MARKER ONLY -- NOT AN APPLICATION MIGRATION.
--
-- This version (20260514170223) is already recorded as applied in the
-- shared production Supabase project (dbupuphezeqkiolprrlg / usam-website).
--
-- The schema it originally created (public.financial_intake_links,
-- public.financial_intake_submissions, public.financial_intake_files) is
-- NOT owned or used by the usam-website application. There are zero
-- references to these tables anywhere in this repository's app/ or src/
-- directories, and zero mention of this feature in this repository's
-- commit history. The usam-website app's actual, current intake system is
-- public.financial_freedom_inquiries (see 20260501203857_*.sql and
-- related migrations), which is unrelated to this table set.
--
-- This file exists solely so the Supabase CLI's local migration history
-- matches the remote ledger for this shared database -- so that
-- `supabase migration list` and `supabase db push` behave correctly for
-- migrations this repository DOES own, without being blocked by a version
-- this repository does not own.
--
-- This file must never be edited to add real DDL. It must not recreate,
-- alter, or remove the external schema described above. If that schema
-- needs to change, it must be done from whatever project/repository
-- actually owns it, not from here.
